import { rookieUIDebugWarn } from "../rookieui_debug_deps.js";
import { fetchRookieUIResource, toErrorDetail } from "./rookieui_api_transport.js";
import { CONTROLNET_UNION_CONTRACT_FALLBACK } from "./rookieui_controlnet_resources.js";
import { POLICY_CONTRACT_VERSION, resolveEffectiveParameterPolicy } from "../rookieui_effective_parameter_policy.js";
import { buildModelFamilyStableProjection } from "../rookieui_family_profile_projection.js";
import {
  FLUX_KREA_DEV_FALLBACK_ENTRY,
  QWEN_IMAGE_EDIT_2511_FALLBACK_ENTRY,
} from "../rookieui_family_profile_fallback_entries.js";

const CURRENT_HOST_DEFERRED_PROFILE_IDS = new Set([
  "klein_4b_distilled",
  "klein_9b_distilled",
  "qwen_image_edit_multi_lora",
]);
const DEFAULT_MODEL_FAMILY_ENTRY_CANDIDATES = [
  {
    id: "sd15",
    title: "Stable Diffusion 1.5",
    translation_base_family: "sd15",
    public_base_family: "sd15",
    prompt_encoder: "clip_text_encode",
    default_width: 512,
    default_height: 512,
    default_steps: 28,
    default_cfg_scale: 7.0,
    default_sampler: "euler_ancestral",
    default_scheduler: "normal",
    default_clip_skip: 1,
    supports_clip_skip: true,
    primary_model_category: "checkpoints",
    text_encoder_visible: false,
    support_tier: "parity",
    compatibility_summary: "Primary A1111 parity baseline for classic Stable Diffusion checkpoints.",
    experimental: false,
    aliases: [],
    notes: [
      "Primary A1111 baseline for classic Stable Diffusion checkpoints.",
      "Uses standard CLIP text encoding and optional clip-skip projection.",
    ],
  },
  {
    id: "sdxl",
    title: "Stable Diffusion XL",
    translation_base_family: "sdxl",
    public_base_family: "sdxl",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 28,
    default_cfg_scale: 7.0,
    default_sampler: "dpmpp_2m",
    default_scheduler: "karras",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "checkpoints",
    text_encoder_visible: false,
    support_tier: "parity",
    compatibility_summary: "Primary SDXL parity baseline with dual-text-encoder semantics.",
    experimental: false,
    aliases: [],
    notes: [
      "Uses SDXL dual-text-encoder semantics through CLIPTextEncodeSDXL.",
      "Acts as the baseline for SDXL-derived families in RookieUI parity lanes.",
    ],
  },
  {
    id: "pony",
    title: "Pony",
    translation_base_family: "sdxl",
    public_base_family: "sdxl",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 28,
    default_cfg_scale: 7.0,
    default_sampler: "dpmpp_2m",
    default_scheduler: "karras",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "checkpoints",
    text_encoder_visible: false,
    support_tier: "parity",
    compatibility_summary: "SDXL-derived parity lane with preserved Pony-facing defaults.",
    experimental: false,
    aliases: [],
    notes: ["SDXL-derived parity lane with community-oriented defaults preserved as SDXL translation."],
  },
  {
    id: "illustrious",
    title: "Illustrious",
    translation_base_family: "sdxl",
    public_base_family: "sdxl",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 28,
    default_cfg_scale: 7.0,
    default_sampler: "dpmpp_2m",
    default_scheduler: "karras",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "checkpoints",
    text_encoder_visible: false,
    support_tier: "parity",
    compatibility_summary: "SDXL-derived parity lane retained as an explicit profile.",
    experimental: false,
    aliases: [],
    notes: ["SDXL-derived parity lane retained as an explicit profile for A1111-style UX."],
  },
  {
    id: "noob",
    title: "Noob",
    translation_base_family: "sdxl",
    public_base_family: "sdxl",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 28,
    default_cfg_scale: 7.0,
    default_sampler: "dpmpp_2m",
    default_scheduler: "karras",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "checkpoints",
    text_encoder_visible: false,
    support_tier: "parity",
    compatibility_summary: "SDXL-derived parity lane retained for rookie-safe defaults.",
    experimental: false,
    aliases: [],
    notes: ["SDXL-derived parity lane retained as an explicit profile for rookie-safe defaults."],
  },
  {
    id: "anima",
    title: "Anima",
    translation_base_family: "sdxl",
    public_base_family: "anima",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 30,
    default_cfg_scale: 4.0,
    default_sampler: "er_sde",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary: "Official ComfyUI Anima template preset routed through the non-SD template seam.",
    experimental: true,
    aliases: ["anima preview3"],
    notes: [
      "Matches the official Anima text-to-image template defaults.",
      "Text Encoder selector stays hidden because the official template owns the fixed qwen_3_06b pairing.",
    ],
  },
  {
    id: "chroma",
    title: "Chroma",
    translation_base_family: "sdxl",
    public_base_family: "chroma",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 26,
    default_cfg_scale: 3.5,
    default_sampler: "euler",
    default_scheduler: "beta",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary: "Official ComfyUI Chroma template preset routed through the non-SD template seam.",
    experimental: true,
    aliases: ["chroma1"],
    notes: [
      "Matches the official Chroma text-to-image template defaults.",
      "Text Encoder selector stays hidden because the official template owns the fixed T5 encoder pairing.",
    ],
  },
  {
    id: "ernie_image",
    title: "ERNIE-Image",
    translation_base_family: "sdxl",
    public_base_family: "ernie_image",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 20,
    default_cfg_scale: 4.0,
    default_sampler: "euler",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary: "Official ComfyUI ERNIE-Image template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["ernie-image", "ernie image"],
    notes: [
      "Matches the official ERNIE-Image template defaults.",
      "Text Encoder selector stays hidden because the official template owns both the Ministral and prompt-enhancer pairing.",
    ],
  },
  {
    id: "ernie_image_turbo",
    title: "ERNIE-Image Turbo",
    translation_base_family: "sdxl",
    public_base_family: "ernie_image",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 8,
    default_cfg_scale: 1.0,
    default_sampler: "euler",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary: "Official ComfyUI ERNIE-Image Turbo template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["ernie-image-turbo", "ernie image turbo"],
    notes: [
      "Matches the official ERNIE-Image Turbo template defaults.",
      "Text Encoder selector stays hidden because the official template owns both the Ministral and prompt-enhancer pairing.",
    ],
  },
  {
    id: "flux",
    title: "Flux.1 Dev FP8",
    translation_base_family: "sdxl",
    public_base_family: "flux",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 20,
    default_cfg_scale: 1.0,
    default_sampler: "euler",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary: "Official ComfyUI Flux.1 Dev FP8 template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["flux.1 dev fp8", "flux-1 dev fp8", "flux1 dev fp8"],
    notes: [
      "Matches the official Flux.1 Dev FP8 template defaults.",
      "Text Encoder selector stays hidden because the official template owns the dual-encoder bundle.",
      "Template LoRA stays explicit and defaults to the official turbo LoRA, but may be overridden with truthful drift messaging.",
    ],
  },
  FLUX_KREA_DEV_FALLBACK_ENTRY,
  {
    id: "flux2_dev",
    title: "Flux.2 Dev",
    translation_base_family: "sdxl",
    public_base_family: "flux2",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 20,
    default_cfg_scale: 1.0,
    default_sampler: "euler",
    default_scheduler: "beta",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary: "Official ComfyUI Flux.2 Dev txt2img template preset on the dedicated Flux2 sampler seam.",
    experimental: true,
    aliases: ["flux.2 dev", "flux2 dev", "flux 2 dev"],
    notes: [
      "Matches the official Flux.2 Dev txt2img template defaults.",
      "Text Encoder selector stays hidden because the official template owns the mistral_3_small_flux2 pairing.",
      "Template LoRA stays explicit and defaults to the official Flux.2 Turbo LoRA.",
    ],
  },
  {
    id: "ideogram4",
    title: "Ideogram v4",
    translation_base_family: "sdxl",
    public_base_family: "ideogram4",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 20,
    default_cfg_scale: 7.0,
    default_sampler: "euler",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary:
      "Official ComfyUI Ideogram v4 local text-to-image template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["ideogram", "ideogram v4", "ideogram4"],
    ideogram_modes: ["quality", "default", "turbo"],
    default_ideogram_mode: "default",
    notes: [
      "Matches the official local Ideogram v4 text-to-image template defaults.",
      "Text Encoder selector stays hidden because the official template owns the fixed qwen3vl_8b pairing.",
      "The required unconditional Ideogram model is a hidden official graph asset, not a separate RookieUI selector.",
      "API-provider Ideogram remains unsupported.",
    ],
  },
  {
    id: "krea2_turbo",
    title: "Krea-2 Turbo",
    translation_base_family: "sdxl",
    public_base_family: "krea2",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 8,
    default_cfg_scale: 1.0,
    default_sampler: "euler",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary:
      "Official ComfyUI Krea-2 Turbo local text-to-image template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["krea2", "krea 2", "krea-2", "krea2 turbo", "krea-2 turbo"],
    notes: [
      "Matches the official local Krea-2 Turbo text-to-image template defaults.",
      "Text Encoder selector stays hidden because the official template owns the fixed qwen3vl_4b pairing.",
      "Template LoRA remains optional and is only applied when resolved from host inventory or user selection.",
      "API-provider and style-reference Krea workflows remain unsupported.",
    ],
  },
  {
    id: "klein_4b_distilled",
    title: "Flux.2 4B Distilled Klein",
    translation_base_family: "sdxl",
    public_base_family: "klein",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 4,
    default_cfg_scale: 1.0,
    default_sampler: "euler",
    default_scheduler: "beta",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary:
      "Official ComfyUI Flux.2 4B Distilled Klein template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["flux.2 4b distilled klein", "klein 4b distilled"],
    notes: [
      "Matches the official Flux.2 4B Distilled Klein template defaults.",
      "Text Encoder selector stays hidden because the official template owns the fixed qwen_3_4b pairing.",
    ],
  },
  {
    id: "klein_4b",
    title: "Flux.2 4B Klein",
    translation_base_family: "sdxl",
    public_base_family: "klein",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 20,
    default_cfg_scale: 5.0,
    default_sampler: "euler",
    default_scheduler: "beta",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary: "Official ComfyUI Flux.2 4B Klein template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["klein", "flux.2", "flux2", "flux.2 4b klein", "klein 4b"],
    notes: [
      "Matches the official Flux.2 4B Klein template defaults.",
      "Text Encoder selector stays hidden because the official template owns the fixed qwen_3_4b pairing.",
    ],
  },
  {
    id: "klein_9b_distilled",
    title: "Flux.2 9B Distilled Klein",
    translation_base_family: "sdxl",
    public_base_family: "klein",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 4,
    default_cfg_scale: 1.0,
    default_sampler: "euler",
    default_scheduler: "beta",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary:
      "Official ComfyUI Flux.2 9B Distilled Klein template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["flux.2 9b distilled klein", "klein 9b distilled"],
    notes: [
      "Matches the official Flux.2 9B Distilled Klein template defaults.",
      "Text Encoder selector stays hidden because the official template owns the fixed qwen_3_8b pairing.",
    ],
  },
  {
    id: "klein_9b",
    title: "Flux.2 9B Klein",
    translation_base_family: "sdxl",
    public_base_family: "klein",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 20,
    default_cfg_scale: 5.0,
    default_sampler: "euler",
    default_scheduler: "beta",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary: "Official ComfyUI Flux.2 9B Klein template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["flux.2 9b klein", "klein 9b"],
    notes: [
      "Matches the official Flux.2 9B Klein template defaults.",
      "Text Encoder selector stays hidden because the official template owns the fixed qwen_3_8b pairing.",
    ],
  },
  {
    id: "hidream_i1_dev_fp8",
    title: "HiDream i1 Dev FP8",
    translation_base_family: "sdxl",
    public_base_family: "hidream",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 28,
    default_cfg_scale: 1.0,
    default_sampler: "lcm",
    default_scheduler: "normal",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary:
      "Official ComfyUI HiDream i1 Dev FP8 template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["hidream i1 dev fp8"],
    notes: [
      "Matches the official HiDream i1 Dev FP8 template defaults.",
      "Text Encoder selector stays hidden because the official template owns the four-encoder bundle.",
    ],
  },
  {
    id: "hidream_i1_fast",
    title: "HiDream i1 fast",
    translation_base_family: "sdxl",
    public_base_family: "hidream",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 16,
    default_cfg_scale: 1.0,
    default_sampler: "lcm",
    default_scheduler: "normal",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary:
      "Official ComfyUI HiDream i1 fast template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["hidream i1 fast"],
    notes: [
      "Matches the official HiDream i1 fast template defaults.",
      "Text Encoder selector stays hidden because the official template owns the four-encoder bundle.",
    ],
  },
  {
    id: "hidream_i1_full",
    title: "HiDream i1 full",
    translation_base_family: "sdxl",
    public_base_family: "hidream",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 50,
    default_cfg_scale: 5.0,
    default_sampler: "uni_pc",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary:
      "Official ComfyUI HiDream i1 full template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["hidream", "hidream i1", "hidream i1 full"],
    notes: [
      "Matches the official HiDream i1 full template defaults.",
      "Text Encoder selector stays hidden because the official template owns the four-encoder bundle.",
    ],
  },
  {
    id: "longcat_image",
    title: "Longcat BF16",
    translation_base_family: "sdxl",
    public_base_family: "longcat_image",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 20,
    default_cfg_scale: 4.0,
    default_sampler: "euler",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary: "Official ComfyUI Longcat BF16 template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["longcat", "longcat image"],
    notes: [
      "Matches the official Longcat BF16 template defaults.",
      "Text Encoder selector stays hidden because the official template owns the fixed qwen_2.5_vl pairing.",
    ],
  },
  {
    id: "qwen_image",
    title: "Qwen-Image 2512",
    translation_base_family: "sdxl",
    public_base_family: "qwen_image",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1328,
    default_height: 1328,
    default_steps: 50,
    default_cfg_scale: 4.0,
    default_sampler: "euler",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary:
      "Official ComfyUI Qwen-Image 2512 template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["qwen image", "qwen-image 2512", "qwen image 2512"],
    notes: [
      "Matches the official Qwen-Image 2512 template defaults.",
      "Text Encoder selector stays hidden because the official template owns the fixed qwen_2.5_vl pairing.",
      "Template LoRA stays explicit and defaults to the official 4-step Lightning LoRA, but may be overridden with truthful drift messaging.",
    ],
  },
  {
    id: "qwen_image_edit",
    title: "Qwen-Image Edit",
    translation_base_family: "sdxl",
    public_base_family: "qwen_image_edit",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1328,
    default_height: 1328,
    default_steps: 4,
    default_cfg_scale: 1.0,
    default_sampler: "euler",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary:
      "Legacy Qwen-Image Edit compatibility preset retained on the dedicated edit-flow seam.",
    experimental: true,
    aliases: ["qwen image edit", "qwen-image edit"],
    notes: [
      "Retains the pre-2511 Qwen-Image Edit compatibility defaults.",
      "Edit flow requires a source image but does not require a mask.",
      "Current Qwen 2509 plus-encoder parity is not silently substituted for this saved-request lane.",
      "Template LoRA stays explicit and defaults to the official lightning LoRA, but may be overridden with truthful drift messaging.",
    ],
  },
  QWEN_IMAGE_EDIT_2511_FALLBACK_ENTRY,
  {
    id: "qwen_image_edit_multi_lora",
    title: "Qwen-Image Edit Multi-LoRA",
    translation_base_family: "sdxl",
    public_base_family: "qwen_image_edit",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1328,
    default_height: 1328,
    default_steps: 4,
    default_cfg_scale: 1,
    default_sampler: "euler",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary:
      "Official ComfyUI Qwen-Image Edit multi-LoRA template preset on the dedicated edit-flow seam.",
    experimental: true,
    aliases: ["qwen image edit multi lora", "qwen-image edit multi lora", "qwen image edit triple lora"],
    notes: [
      "Matches the official Qwen-Image Edit multi-LoRA template defaults.",
      "Edit flow requires a source image and does not require a mask.",
      "Template-owned lightning LoRA is stacked three times before any inline LoRA overrides.",
    ],
  },
  {
    id: "firered_image_edit",
    title: "FireRed Image Edit",
    translation_base_family: "sdxl",
    public_base_family: "firered_image_edit",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1328,
    default_height: 1328,
    default_steps: 40,
    default_cfg_scale: 4,
    default_sampler: "euler",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary:
      "Official ComfyUI FireRed Image Edit 1.1 base template preset on the dedicated edit-flow seam.",
    experimental: true,
    aliases: ["firered image edit", "fire red image edit", "firered", "fire red"],
    notes: [
      "Matches the official FireRed Image Edit base template branch defaults.",
      "Edit flow requires one to three ordered source images and does not require a mask.",
      "This base lane keeps the official non-lightning branch and does not require a template-owned LoRA.",
    ],
  },
  {
    id: "firered_image_edit_lightning",
    title: "FireRed Image Edit Lightning",
    translation_base_family: "sdxl",
    public_base_family: "firered_image_edit",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1328,
    default_height: 1328,
    default_steps: 8,
    default_cfg_scale: 1,
    default_sampler: "euler",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary:
      "Official ComfyUI FireRed Image Edit 1.1 lightning template branch preset on the dedicated edit-flow seam.",
    experimental: true,
    aliases: [
      "firered image edit lightning",
      "fire red image edit lightning",
      "firered lightning",
      "fire red lightning",
    ],
    notes: [
      "Matches the official FireRed Image Edit lightning branch defaults.",
      "Edit flow requires one to three ordered source images and does not require a mask.",
      "Template LoRA stays explicit and defaults to the official FireRed lightning branch LoRA, but may be overridden with truthful drift messaging.",
    ],
  },
  {
    id: "flux_kontext_dev_edit",
    title: "Flux.1 Kontext Dev Edit",
    translation_base_family: "sdxl",
    public_base_family: "flux_kontext_dev_edit",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 20,
    default_cfg_scale: 1,
    default_sampler: "euler",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary:
      "Official ComfyUI Flux.1 Kontext Dev image-edit template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["flux.1 kontext dev edit", "flux kontext edit", "kontext edit"],
    notes: [
      "Matches the official Flux.1 Kontext Dev image-edit template defaults.",
      "Edit flow supports ordered multi-reference stitching and does not require a mask.",
      "The main reference image is used as the first stitched anchor in RookieUI's bounded first-wave adapter.",
    ],
  },
  {
    id: "flux2_image_edit",
    title: "Flux.2 Image Edit",
    translation_base_family: "sdxl",
    public_base_family: "flux2_image_edit",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1248,
    default_height: 832,
    default_steps: 20,
    default_cfg_scale: 4,
    default_sampler: "euler",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary:
      "Official ComfyUI Flux.2 image-edit template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["flux.2 image edit", "flux2 image edit"],
    notes: [
      "Matches the current Flux.2 image-edit template dimensions and core assets.",
      "Edit flow requires one ordered source image and does not require a mask.",
      "The optional turbo-LoRA branch remains out of scope until a dedicated profile is planned.",
    ],
  },
  {
    id: "klein_9b_kv_image_edit",
    title: "Flux.2 Klein 9B KV Image Edit",
    translation_base_family: "sdxl",
    public_base_family: "klein_9b_kv_image_edit",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 4,
    default_cfg_scale: 1,
    default_sampler: "euler",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary:
      "Legacy Flux.2 Klein 9B KV image-edit compatibility preset retained on the current non-SD translation seam.",
    experimental: true,
    aliases: ["flux.2 klein 9b kv image edit", "klein 9b kv image edit", "klein kv edit"],
    notes: [
      "Retains the older Flux.2 Klein 9B KV image-edit template defaults.",
      "Edit flow supports ordered multi-reference images and does not require a mask.",
      "The first-wave adapter keeps a bounded three-reference cap even though the shared latent chain can extend further.",
      "The current blueprint set exposes a separate Flux.2 Klein 4B image-edit blueprint that remains deferred from this drift sweep.",
    ],
  },
  {
    id: "longcat_image_edit",
    title: "Longcat Image Edit",
    translation_base_family: "sdxl",
    public_base_family: "longcat_image_edit",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 50,
    default_cfg_scale: 4.5,
    default_sampler: "euler",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary:
      "Official ComfyUI Longcat image-edit template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["longcat image edit", "longcat edit"],
    notes: [
      "Matches the official Longcat image-edit template defaults.",
      "Edit flow requires one ordered source image and does not require a mask.",
      "Longcat edit keeps the Qwen-style edit encoder but applies Flux-family reference-method metadata before sampling.",
    ],
  },
  {
    id: "z_image",
    title: "Z-Image",
    translation_base_family: "sdxl",
    public_base_family: "z_image",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 25,
    default_cfg_scale: 4.0,
    default_sampler: "res_multistep",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary: "Official ComfyUI Z-Image template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["lumina", "z-image", "z image", "lumina2"],
    notes: [
      "Matches the official Z-Image template defaults.",
      "Text Encoder selector stays hidden because the official template owns the fixed qwen_3_4b pairing.",
    ],
  },
  {
    id: "z_image_turbo",
    title: "Z-Image Turbo",
    translation_base_family: "sdxl",
    public_base_family: "z_image",
    prompt_encoder: "clip_text_encode_sdxl",
    default_width: 1024,
    default_height: 1024,
    default_steps: 8,
    default_cfg_scale: 1.0,
    default_sampler: "res_multistep",
    default_scheduler: "simple",
    default_clip_skip: 1,
    supports_clip_skip: false,
    primary_model_category: "diffusion_models",
    text_encoder_visible: false,
    support_tier: "family-adapted",
    compatibility_summary: "Official ComfyUI Z-Image Turbo template preset on the current non-SD translation seam.",
    experimental: true,
    aliases: ["zit", "z-image-turbo", "z image turbo"],
    notes: [
      "Matches the official Z-Image Turbo template defaults.",
      "Text Encoder selector stays hidden because the official template owns the fixed qwen_3_4b pairing.",
    ],
  },
];
// IMPORTANT: keep fallback exposure fail-closed when the backend is unavailable.
export const DEFAULT_MODEL_FAMILY_ENTRIES = Object.freeze(
  DEFAULT_MODEL_FAMILY_ENTRY_CANDIDATES.filter((entry) => !CURRENT_HOST_DEFERRED_PROFILE_IDS.has(entry.id)),
);

const DEFAULT_PARITY_PROFILES = Object.freeze(
  DEFAULT_MODEL_FAMILY_ENTRIES.map((entry) => ({
    id: entry.id,
    title: entry.title,
    base_family: entry.translation_base_family,
    prompt_encoder: entry.prompt_encoder,
    default_width: entry.default_width,
    default_height: entry.default_height,
    default_steps: entry.default_steps,
    default_cfg_scale: entry.default_cfg_scale,
    default_sampler: entry.default_sampler,
    default_scheduler: entry.default_scheduler,
    default_clip_skip: entry.default_clip_skip,
    supports_clip_skip: entry.supports_clip_skip,
    notes: [...entry.notes],
  })),
);

const PROMPT_ENHANCEMENT_ON = Object.freeze({
  prompt_enhancement_visible: true,
  default_prompt_enhancement_enabled: true,
});

const DEFAULT_TEMPLATE_PARAMETER_OVERRIDES = Object.freeze({
  chroma: { shift_visible: true, default_shift: 1 },
  ernie_image: PROMPT_ENHANCEMENT_ON,
  ernie_image_turbo: PROMPT_ENHANCEMENT_ON,
  hidream_i1_dev_fp8: { shift_visible: true, default_shift: 6 },
  hidream_i1_fast: { shift_visible: true, default_shift: 3 },
  hidream_i1_full: { shift_visible: true, default_shift: 3 },
  flux: {
    template_lora_visible: true,
    template_lora_override_allowed: true,
    official_template_lora_label: "Flux_2-Turbo-LoRA_comfyui.safetensors",
    default_template_lora_enabled: true,
  },
  flux2_dev: {
    flux_guidance_visible: true,
    default_flux_guidance: 4.0,
    template_lora_visible: true,
    template_lora_override_allowed: true,
    official_template_lora_label: "Flux_2-Turbo-LoRA_comfyui.safetensors",
    default_template_lora_enabled: false,
    default_template_lora_strength: 1.0,
  },
  krea2_turbo: {
    ...PROMPT_ENHANCEMENT_ON,
    template_lora_visible: true,
    template_lora_override_allowed: true,
    official_template_lora_label: "krea2_darkbrush.safetensors",
    default_template_lora_enabled: false,
    default_template_lora_strength: 0.8,
    default_template_lora_trigger_word: "monochrome ink wash style",
    template_lora_trigger_visible: true,
  },
  longcat_image: { flux_guidance_visible: true, default_flux_guidance: 4.0 },
  qwen_image: {
    shift_visible: true,
    default_shift: 3.1,
    template_lora_visible: true,
    template_lora_override_allowed: true,
    official_template_lora_label: "Qwen-Image-2512-Lightning-4steps-V1.0-fp32.safetensors",
    default_template_lora_enabled: true,
  },
  qwen_image_edit: {
    shift_visible: true,
    default_shift: 3.0,
    edit_megapixels_visible: true,
    default_edit_megapixels: 1.5,
    template_lora_visible: true,
    template_lora_override_allowed: true,
    official_template_lora_label: "Qwen-Image-Edit-Lightning-4steps-V1.0-bf16.safetensors",
    default_template_lora_enabled: true,
    image_edit_profile: true,
    request_contract_surface: "img2img",
    reference_input_mode: "single",
    max_direct_references: 1,
    encoder_family: "qwen_image_edit",
    template_lora_chain_mode: "single",
    available_surface_flows: ["img2img"],
  },
  qwen_image_edit_2511: {
    shift_visible: true,
    default_shift: 3.1,
    image_edit_profile: true,
    request_contract_surface: "img2img",
    reference_input_mode: "multi",
    max_direct_references: 3,
    encoder_family: "qwen_image_edit_2511",
    template_lora_chain_mode: "none",
    available_surface_flows: ["img2img"],
  },
  qwen_image_edit_multi_lora: {
    shift_visible: true,
    default_shift: 3.0,
    edit_megapixels_visible: true,
    default_edit_megapixels: 1.5,
    template_lora_visible: true,
    template_lora_override_allowed: true,
    official_template_lora_label: "Qwen-Image-Edit-Lightning-4steps-V1.0-bf16.safetensors",
    default_template_lora_enabled: true,
    image_edit_profile: true,
    request_contract_surface: "img2img",
    reference_input_mode: "single",
    max_direct_references: 1,
    encoder_family: "qwen_image_edit",
    template_lora_chain_mode: "triple",
    available_surface_flows: ["img2img"],
  },
  firered_image_edit: {
    shift_visible: true,
    default_shift: 3.1,
    edit_megapixels_visible: true,
    default_edit_megapixels: 1.0,
    image_edit_profile: true,
    request_contract_surface: "img2img",
    reference_input_mode: "multi",
    max_direct_references: 3,
    encoder_family: "qwen_image_edit_plus",
    template_lora_chain_mode: "none",
    available_surface_flows: ["img2img"],
  },
  firered_image_edit_lightning: {
    shift_visible: true,
    default_shift: 3.1,
    edit_megapixels_visible: true,
    default_edit_megapixels: 1.0,
    template_lora_visible: true,
    template_lora_override_allowed: true,
    official_template_lora_label: "FireRed-Image-Edit-1.0-Lightning-8steps-v1.0.safetensors",
    default_template_lora_enabled: true,
    image_edit_profile: true,
    request_contract_surface: "img2img",
    reference_input_mode: "multi",
    max_direct_references: 3,
    encoder_family: "qwen_image_edit_plus",
    template_lora_chain_mode: "single",
    available_surface_flows: ["img2img"],
  },
  flux_kontext_dev_edit: {
    flux_guidance_visible: true,
    default_flux_guidance: 2.5,
    image_edit_profile: true,
    request_contract_surface: "img2img",
    reference_input_mode: "multi",
    max_direct_references: 3,
    encoder_family: "flux_clip_text",
    template_lora_chain_mode: "none",
    available_surface_flows: ["img2img"],
  },
  flux2_image_edit: {
    flux_guidance_visible: true,
    default_flux_guidance: 4.0,
    edit_megapixels_visible: true,
    default_edit_megapixels: 1.0,
    image_edit_profile: true,
    request_contract_surface: "img2img",
    reference_input_mode: "single",
    max_direct_references: 1,
    encoder_family: "flux_clip_text",
    template_lora_chain_mode: "none",
    available_surface_flows: ["img2img"],
  },
  klein_9b_kv_image_edit: {
    edit_megapixels_visible: true,
    default_edit_megapixels: 1.0,
    image_edit_profile: true,
    request_contract_surface: "img2img",
    reference_input_mode: "multi",
    max_direct_references: 3,
    encoder_family: "flux_clip_text",
    template_lora_chain_mode: "none",
    available_surface_flows: ["img2img"],
  },
  longcat_image_edit: {
    flux_guidance_visible: true,
    default_flux_guidance: 4.5,
    edit_megapixels_visible: true,
    default_edit_megapixels: 1.0,
    image_edit_profile: true,
    request_contract_surface: "img2img",
    reference_input_mode: "single",
    max_direct_references: 1,
    encoder_family: "qwen_image_edit",
    template_lora_chain_mode: "none",
    available_surface_flows: ["img2img"],
  },
  z_image: { shift_visible: true, default_shift: 3.0 },
  z_image_turbo: { shift_visible: true, default_shift: 3.0 },
});

export const DEFAULT_MODEL_FAMILY_REGISTRY_ENTRIES = Object.freeze(
  DEFAULT_MODEL_FAMILY_ENTRIES.map((entry) => ({
    shift_visible: false,
    default_shift: null,
    flux_guidance_visible: false,
    default_flux_guidance: null,
    prompt_enhancement_visible: false,
    default_prompt_enhancement_enabled: false,
    edit_megapixels_visible: false,
    default_edit_megapixels: null,
    template_lora_visible: false,
    template_lora_override_allowed: false,
    official_template_lora_label: "",
    default_template_lora_enabled: false,
    default_template_lora_strength: 1.0,
    default_template_lora_trigger_word: "",
    template_lora_trigger_visible: false,
    image_edit_profile: false,
    request_contract_surface: "",
    reference_input_mode: "none",
    max_direct_references: 0,
    encoder_family: "",
    template_lora_chain_mode: "none",
    ideogram_modes: [],
    default_ideogram_mode: "",
    available_surface_flows: entry.support_tier === "parity" ? ["txt2img", "img2img"] : ["txt2img"],
    ...entry,
    ...(DEFAULT_TEMPLATE_PARAMETER_OVERRIDES[entry.id] ?? {}),
    ...resolveEffectiveParameterPolicy(entry.id),
  })),
);

export const DEFAULT_PRIMARY_MODEL_CATEGORY_BY_FAMILY = Object.freeze(
  DEFAULT_MODEL_FAMILY_ENTRIES.reduce((categoryMap, entry) => {
    const keys = new Set([entry.id, entry.public_base_family, ...entry.aliases]);
    keys.forEach((key) => {
      if (typeof key === "string" && key.trim()) {
        categoryMap[key] = entry.primary_model_category;
      }
    });
    return categoryMap;
  }, {}),
);

const DEFAULT_PRESETS = Object.freeze(
  DEFAULT_MODEL_FAMILY_REGISTRY_ENTRIES.map((entry) => ({
    id: entry.id,
    title: entry.id === "sd15" ? "SD1.5" : entry.id === "sdxl" ? "SDXL" : entry.title,
    profile: entry.id,
    base_family: entry.public_base_family,
    checkpoint_name: "__host_default__",
    vae_name: "Automatic",
    text_encoder_name: "Automatic",
    template_lora_name: "",
    template_lora_enabled: Boolean(entry.default_template_lora_enabled),
    template_lora_strength: Number(entry.default_template_lora_strength ?? 1),
    template_lora_trigger_word: entry.default_template_lora_trigger_word ?? "",
    width: entry.default_width,
    height: entry.default_height,
    steps: entry.default_steps,
    cfg_scale: entry.default_cfg_scale,
    shift: entry.default_shift ?? null,
    flux_guidance: entry.default_flux_guidance ?? null,
    sampler_name: entry.default_sampler,
    scheduler_name: entry.scheduler_control_mode === "generic" ? entry.default_scheduler : "",
    clip_skip: entry.default_clip_skip,
    prompt_enhancement_enabled: Boolean(entry.default_prompt_enhancement_enabled),
    edit_megapixels: entry.default_edit_megapixels ?? null,
    image_edit_profile: Boolean(entry.image_edit_profile),
    request_contract_surface: entry.request_contract_surface ?? "",
    reference_input_mode: entry.reference_input_mode ?? "none",
    max_direct_references: entry.max_direct_references ?? 0,
    encoder_family: entry.encoder_family ?? "",
    template_lora_chain_mode: entry.template_lora_chain_mode ?? "none",
    scheduler_control_mode: entry.scheduler_control_mode,
    negative_prompt_mode: entry.negative_prompt_mode,
    ideogram_mode: entry.default_ideogram_mode ?? "",
  })),
);

export const DEFAULT_NEWER_FAMILY_PROFILES = Object.freeze(
  DEFAULT_MODEL_FAMILY_ENTRIES.filter((entry) => entry.support_tier !== "parity").map((entry) => ({
    id: entry.id,
    title: entry.title,
    summary: entry.compatibility_summary,
    default: false,
    experimental: entry.experimental,
    aliases: [...entry.aliases],
  })),
);

const DEFAULT_CAPABILITIES = Object.freeze({
  service: "rookieui",
  visibility: "internal",
  // IMPORTANT: shell version must come from backend capabilities (pyproject source of truth).
  shell_version: "",
  host_surfaces: ["standalone-web", "desktop"],
  features: {
    sidebarShell: true,
    capabilityBootstrap: true,
    parityMatrix: true,
    workflowTranslation: true,
    modelInventory: true,
    presets: true,
    compatibilityLayer: true,
    txt2img: true,
    img2img: true,
    adetailer: true,
    controlnet: true,
    pngInfo: true,
    queue: true,
    xyzPlot: true,
  },
  tabs: [
    { id: "txt2img", title: "Txt2Img", state: "active", enabled: true },
    { id: "img2img", title: "Img2Img", state: "active", enabled: true },
    { id: "extras", title: "Extras", state: "active", enabled: true },
    { id: "pnginfo", title: "PNG Info", state: "active", enabled: true },
    { id: "queue", title: "Queue", state: "active", enabled: true },
  ],
  parity: {
    profiles: DEFAULT_PARITY_PROFILES,
    sampler_aliases: {
      samplers: { "euler a": "euler_ancestral", "dpm++ 2m": "dpmpp_2m" },
      scheduler_aliases: { automatic: "normal", ddim: "ddim_uniform" },
      scheduler_overrides: { "dpm++ 2m karras": "karras" },
      supported_schedulers: [
        "normal",
        "karras",
        "exponential",
        "sgm_uniform",
        "simple",
        "ddim_uniform",
        "beta",
        "linear_quadratic",
        "kl_optimal",
      ],
    },
  },
  model_families: {
    contract_version: POLICY_CONTRACT_VERSION,
    entries: DEFAULT_MODEL_FAMILY_REGISTRY_ENTRIES,
  },
  prompt_semantics: {
    contract_version: "r55-20260411",
    contract_scope: "sd-family-first",
    rollout: {
      default_mode: "semantic_v2",
      legacy_fallback_env: "ROOKIEUI_PROMPT_DSL_LEGACY",
      warning_code_contract: "stable",
    },
    compiler_constraints: {
      conditioning_nodes: ["ConditioningCombine", "ConditioningConcat", "ConditioningSetTimestepRange"],
      execution_backend: "ComfyUI graph translation",
    },
    capabilities: [
      {
        id: "and_composition",
        title: "AND Composition",
        a1111_semantics: "Composable multi-condition prompt branches via AND and optional branch weight suffix.",
        rookieui_contract: "Parsed and compiled to multi-branch conditioning composition for SD-family execution lanes.",
        status: "supported",
        translation: "conditioning_combine",
        reference: "a1111_prompt_parser",
      },
      {
        id: "break_chunks",
        title: "BREAK Chunking",
        a1111_semantics: "BREAK token splits prompt chunks for chunked conditioning behavior.",
        rookieui_contract: "Parsed into prompt chunks and compiled with explicit chunk-composition nodes.",
        status: "supported",
        translation: "conditioning_concat",
        reference: "a1111_prompt_parser",
      },
      {
        id: "prompt_scheduling",
        title: "Prompt Scheduling",
        a1111_semantics: "Schedule syntax [from:to:at] swaps text by step-progress.",
        rookieui_contract: "Parsed into schedule slices and compiled with timestep range conditioning.",
        status: "supported",
        translation: "conditioning_set_timestep_range",
        reference: "a1111_prompt_parser",
      },
      {
        id: "attention_weighting",
        title: "Attention Weighting",
        a1111_semantics: "Parenthesis/bracket prompt attention and explicit (text:weight) weighting.",
        rookieui_contract: "Structured detection with SD-family-first weighted text preservation.",
        status: "supported",
        translation: "weighted_text_tokens",
        reference: "a1111_prompt_parser",
      },
      {
        id: "extra_network_lora",
        title: "Extra Network (LoRA/LyCORIS)",
        a1111_semantics: "Inline extra-network token <lora:...> / <lyco:...> merges into model graph.",
        rookieui_contract: "Deterministic extraction + merged activation chain through LoraLoader nodes.",
        status: "supported",
        translation: "lora_loader_chain",
        reference: "a1111_extra_networks",
      },
      {
        id: "extra_network_other",
        title: "Extra Network (Unsupported Families)",
        a1111_semantics: "Non-LoRA extra network token families in prompt body.",
        rookieui_contract: "Removed from prompt payload with explicit warning diagnostics.",
        status: "guarded",
        translation: "warning_and_strip",
        reference: "a1111_extra_networks",
      },
    ],
  },
  adetailer: {
    contract: {
      version: "r74f77-20260414",
      ui_variant: "a1111_integrated_detailer",
      unit_count: 4,
      prompt_tokens: ["[PROMPT]", "[SEP]", "[SKIP]"],
      controlnet_modes: ["none", "passthrough", "custom"],
      detector_provider_families: ["none", "ultralytics_bbox", "ultralytics_segm", "mediapipe_face"],
      detector_result_contract: "rookieui_detection_regions_v1",
      controlnet_advanced_contract: {
        version: "r111-20260415",
        weight_presets: ["balanced", "soft", "strong"],
        supports_layer_weights: true,
        supports_timestep_keyframes: true,
        supports_mask_aware_apply: true,
        runtime_state: "rookieui_native_advanced_runtime",
      },
      controlnet_union_contract: CONTROLNET_UNION_CONTRACT_FALLBACK,
      mask_filter_methods: ["Area", "Confidence"],
      mask_merge_modes: ["None", "Merge", "Merge and Invert"],
      defaults: {
        detector: "None",
        detector_classes: "",
        confidence: 0.3,
        mask_filter_method: "Area",
        mask_k: 0,
        mask_min_ratio: 0.0,
        mask_max_ratio: 1.0,
        x_offset: 0,
        y_offset: 0,
        dilate_erode: 4,
        mask_merge_mode: "None",
        mask_blur: 4,
        denoising_strength: 0.4,
        inpaint_only_masked: true,
        inpaint_padding: 32,
        use_inpaint_size: false,
        inpaint_width: 512,
        inpaint_height: 512,
        use_steps: false,
        steps: 28,
        use_cfg_scale: false,
        cfg_scale: 7.0,
        use_checkpoint: false,
        checkpoint_name: "Use same checkpoint",
        use_vae: false,
        vae_name: "Use same VAE",
        use_sampler: false,
        sampler_name: "DPM++ 2M Karras",
        scheduler_name: "Use same scheduler",
        use_noise_multiplier: false,
        noise_multiplier: 1.0,
        use_clip_skip: false,
        clip_skip: 1,
        restore_face: false,
      },
    },
    behavior_source: "integrated_detailer_contract",
    ui_reference: "localhost_7860_a1111_integrated_host",
    execution_backend: "rookieui_comfy_native_refinement_pipeline",
    skip_img2img_surfaces: ["img2img"],
    controlnet_modes: ["none", "passthrough", "custom"],
    prompt_tokens: ["[PROMPT]", "[SEP]", "[SKIP]"],
    warning_code_contract: "stable_f81",
    availability: {
      execution_backend: "rookieui_comfy_native_refinement_pipeline",
      runtime_stages: ["base_decode", "detect_mask", "inpaint_encode", "refine_sampler", "final_decode"],
      detector_source: "fallback",
      detector_count: 3,
      controlnet_model_count: 0,
      detector_runtime: {
        none: "disabled",
        ultralytics_bbox: "native_runtime_dependency_missing",
        ultralytics_segm: "native_runtime_dependency_missing",
        mediapipe_face: "native_runtime_dependency_missing",
      },
      detector_provider_families: ["none", "ultralytics_bbox", "ultralytics_segm", "mediapipe_face"],
      degraded_warning_codes: [
        "ADETAILER_DETECTOR_NOT_IN_CATALOG",
        "ADETAILER_DETECTOR_RUNTIME_FALLBACK_MASK",
        "ADETAILER_CONTROLNET_PASSTHROUGH_EMPTY",
        "ADETAILER_CONTROLNET_CUSTOM_MODEL_MISSING",
      ],
    },
    warning_codes: {
      ADETAILER_UNIT_LIMIT_TRUNCATED: "ADetailer unit payload exceeded the supported 4-unit contract and was truncated.",
      ADETAILER_SKIP_IMG2IMG_IGNORED: "ADetailer skip-img2img is only meaningful for img2img surfaces and was ignored.",
      ADETAILER_NO_ACTIVE_UNITS: "ADetailer is enabled but no enabled unit has a detector selected.",
      ADETAILER_DETECTOR_NOT_IN_CATALOG: "ADetailer detector is not present in the current host catalog; fallback mask behavior may be used.",
      ADETAILER_DETECTOR_RUNTIME_FALLBACK_MASK:
        "ADetailer detector runtime degraded to RookieUI's fallback mask seam for the selected provider family.",
      ADETAILER_CONTROLNET_PASSTHROUGH_EMPTY: "ADetailer ControlNet passthrough was requested but no primary ControlNet unit is enabled.",
      ADETAILER_CONTROLNET_CUSTOM_MODEL_MISSING: "ADetailer custom ControlNet mode was requested without a ControlNet model.",
    },
    routes: ["/rookieui/adetailer/catalog"],
  },
  routes: [
    "/rookieui/health",
    "/rookieui/bootstrap",
    "/rookieui/capabilities",
    "/rookieui/parity",
    "/rookieui/compatibility",
    "/rookieui/models",
    "/rookieui/presets",
    "/rookieui/controlnet/model_list",
    "/rookieui/controlnet/module_list",
    "/rookieui/controlnet/control_types",
    "/rookieui/controlnet/detect",
    "/rookieui/adetailer/catalog",
    "/rookieui/queue",
    "/rookieui/queue/{prompt_id}",
    "/rookieui/xyz-plot/axes",
    "/rookieui/xyz-plot/estimate",
    "/rookieui/xyz-plot/run",
    "/rookieui/xyz-plot/sessions",
    "/rookieui/xyz-plot/sessions/{session_id}",
    "/rookieui/xyz-plot/sessions/{session_id}/cancel",
    "/rookieui/pnginfo/inspect",
    "/rookieui/generate/txt2img",
    "/rookieui/generate/img2img",
    "/rookieui/extras/run",
  ],
});

export function createDefaultCapabilities() {
  return JSON.parse(JSON.stringify(DEFAULT_CAPABILITIES));
}

export async function fetchRookieUICapabilities(fetchImpl = globalThis.fetch) {
  if (typeof fetchImpl !== "function") {
    rookieUIDebugWarn("api.capabilities", "Using fallback capabilities because fetch() is unavailable.");
    return {
      ok: false,
      source: "fallback",
      data: createDefaultCapabilities(),
    };
  }

  try {
    const response = await fetchImpl("/rookieui/capabilities", {
      headers: { Accept: "application/json" },
    });

    if (!response?.ok) {
      throw new Error(`Capability request failed with status ${response?.status ?? "unknown"}`);
    }

    return {
      ok: true,
      source: "server",
      data: await response.json(),
    };
  } catch (_error) {
    rookieUIDebugWarn("api.capabilities", "Capability request failed; returning fallback payload.", {
      error: toErrorDetail(_error),
    });
    return {
      ok: false,
      source: "fallback",
      data: createDefaultCapabilities(),
    };
  }
}

function createFallbackModelInventory() {
  const diagnosticCategories = {
    audio_encoders: "Audio Encoders",
    background_removal: "Background Removal",
    classifiers: "Classifiers",
    configs: "Configs",
    detection: "Detection",
    diffusers: "Diffusers",
    frame_interpolation: "Frame Interpolation",
    geometry_estimation: "Geometry Estimation",
    gligen: "GLIGEN",
    hypernetworks: "Hypernetworks",
    latent_upscale_models: "Latent Upscale Models",
    model_patches: "Model Patches",
    optical_flow: "Optical Flow",
    photomaker: "PhotoMaker",
    style_models: "Style Models",
    ultralytics: "Ultralytics",
    ultralytics_bbox: "Ultralytics BBox",
    ultralytics_segm: "Ultralytics Segm",
    unet: "UNet",
    upscale_models: "Upscale Models",
    vae_approx: "VAE Approx",
  };
  const diagnosticEntries = Object.fromEntries(
    Object.entries(diagnosticCategories).map(([id, title]) => [
      id,
      {
        title,
        items: [],
        default_value: "",
        sidebar_visible: false,
      },
    ]),
  );
  return {
    // IMPORTANT: __host_default__ is an inventory-discovery fallback, not a valid model choice;
    // if it reaches the UI, debug /rookieui/models and /object_info before changing preset defaults.
    source: "fallback",
    ...Object.fromEntries(Object.keys(diagnosticCategories).map((id) => [id, []])),
    checkpoints: ["__host_default__"],
    clip: [],
    clip_vision: [],
    controlnet: [],
    diffusion_models: [],
    vae: ["Automatic"],
    text_encoders: ["Automatic"],
    embeddings: [],
    loras: [],
    default_checkpoint: "__host_default__",
    default_vae: "Automatic",
    default_text_encoder: "Automatic",
    catalog: {
      surface_groups: [
        {
          id: "sd_generation",
          title: "SD Generation",
          categories: ["checkpoints", "diffusion_models", "vae", "text_encoders", "embeddings", "loras"],
        },
        {
          id: "host_diagnostics",
          title: "Host Diagnostics",
          categories: Object.keys(diagnosticCategories),
        },
      ],
      primary_model_category_by_family: { ...DEFAULT_PRIMARY_MODEL_CATEGORY_BY_FAMILY },
      categories: {
        ...diagnosticEntries,
        checkpoints: {
          title: "Checkpoints",
          items: ["__host_default__"],
          default_value: "__host_default__",
          sidebar_visible: true,
        },
        diffusion_models: {
          title: "Diffusion Models",
          items: [],
          default_value: "",
          sidebar_visible: false,
        },
        vae: {
          title: "VAE",
          items: ["Automatic"],
          default_value: "Automatic",
          sidebar_visible: true,
        },
        text_encoders: {
          title: "Text Encoders",
          items: ["Automatic"],
          default_value: "Automatic",
          sidebar_visible: true,
        },
        embeddings: {
          title: "Embeddings",
          items: [],
          default_value: "",
          sidebar_visible: true,
        },
        loras: {
          title: "LoRAs",
          items: [],
          default_value: "",
          sidebar_visible: true,
        },
      },
    },
  };
}

function dedupeStringChoices(values) {
  const result = [];
  const seen = new Set();
  for (const value of values) {
    if (typeof value !== "string") {
      continue;
    }
    const normalized = value.trim();
    if (!normalized || seen.has(normalized)) {
      continue;
    }
    seen.add(normalized);
    result.push(normalized);
  }
  return result;
}

function extractObjectInfoInputChoices(objectInfo, className, fieldName) {
  const nodeInfo = objectInfo?.[className];
  const inputSpec = nodeInfo?.input ?? nodeInfo?.inputs;
  const required = inputSpec?.required && typeof inputSpec.required === "object" ? inputSpec.required : {};
  const optional = inputSpec?.optional && typeof inputSpec.optional === "object" ? inputSpec.optional : {};
  const fieldSpec = required[fieldName] ?? optional[fieldName];
  const choices = Array.isArray(fieldSpec) && Array.isArray(fieldSpec[0]) ? fieldSpec[0] : fieldSpec;
  return Array.isArray(choices) ? dedupeStringChoices(choices) : [];
}

function mergeObjectInfoInputChoices(objectInfo, entries) {
  return dedupeStringChoices(
    entries.flatMap(([className, fieldName]) => extractObjectInfoInputChoices(objectInfo, className, fieldName)),
  );
}

function buildObjectInfoModelInventory(objectInfo) {
  const checkpoints = mergeObjectInfoInputChoices(objectInfo, [["CheckpointLoaderSimple", "ckpt_name"]]);
  const vae = mergeObjectInfoInputChoices(objectInfo, [["VAELoader", "vae_name"]]);
  const diffusionModels = mergeObjectInfoInputChoices(objectInfo, [["UNETLoader", "unet_name"]]);
  const textEncoders = mergeObjectInfoInputChoices(objectInfo, [
    ["CLIPLoader", "clip_name"],
    ["DualCLIPLoader", "clip_name1"],
    ["DualCLIPLoader", "clip_name2"],
    ["TripleCLIPLoader", "clip_name1"],
    ["TripleCLIPLoader", "clip_name2"],
    ["TripleCLIPLoader", "clip_name3"],
    ["QuadrupleCLIPLoader", "clip_name1"],
    ["QuadrupleCLIPLoader", "clip_name2"],
    ["QuadrupleCLIPLoader", "clip_name3"],
    ["QuadrupleCLIPLoader", "clip_name4"],
  ]);
  const loras = mergeObjectInfoInputChoices(objectInfo, [["LoraLoader", "lora_name"]]);
  const controlnet = mergeObjectInfoInputChoices(objectInfo, [["ControlNetLoader", "control_net_name"]]);
  const upscaleModels = mergeObjectInfoInputChoices(objectInfo, [["UpscaleModelLoader", "model_name"]]);
  if (checkpoints.length === 0 && vae.length === 0 && diffusionModels.length === 0) {
    return null;
  }

  const fallback = createFallbackModelInventory();
  const resolvedCheckpoints = checkpoints.length > 0 ? checkpoints : fallback.checkpoints;
  const resolvedVae = vae.length > 0 ? vae : fallback.vae;
  const resolvedTextEncoders = textEncoders.length > 0 ? textEncoders : fallback.text_encoders;
  return {
    ...fallback,
    source: "host-object-info",
    checkpoints: resolvedCheckpoints,
    controlnet,
    diffusion_models: diffusionModels,
    vae: resolvedVae,
    text_encoders: resolvedTextEncoders,
    loras,
    unet: diffusionModels,
    upscale_models: upscaleModels,
    default_checkpoint: resolvedCheckpoints[0],
    default_vae: resolvedVae[0],
    default_text_encoder: resolvedTextEncoders[0],
    catalog: {
      ...fallback.catalog,
      categories: {
        ...fallback.catalog.categories,
        checkpoints: {
          ...fallback.catalog.categories.checkpoints,
          items: resolvedCheckpoints,
          default_value: resolvedCheckpoints[0],
        },
        controlnet: {
          title: "ControlNet",
          items: controlnet,
          default_value: "",
          sidebar_visible: false,
        },
        diffusion_models: {
          ...fallback.catalog.categories.diffusion_models,
          items: diffusionModels,
          default_value: diffusionModels[0] ?? "",
        },
        loras: {
          ...fallback.catalog.categories.loras,
          items: loras,
        },
        text_encoders: {
          ...fallback.catalog.categories.text_encoders,
          items: resolvedTextEncoders,
          default_value: resolvedTextEncoders[0],
        },
        upscale_models: {
          title: "Upscale Models",
          items: upscaleModels,
          default_value: "",
          sidebar_visible: false,
        },
        vae: {
          ...fallback.catalog.categories.vae,
          items: resolvedVae,
          default_value: resolvedVae[0],
        },
      },
    },
  };
}

async function fetchObjectInfoModelInventory(fetchImpl) {
  if (typeof fetchImpl !== "function") {
    return null;
  }
  try {
    // CRITICAL: this is the frontend safety net when RookieUI's Python /models route is stale or unavailable;
    // ComfyUI core still exposes loader selector choices through /object_info.
    const response = await fetchImpl("/object_info", {
      headers: { Accept: "application/json" },
    });
    if (!response?.ok) {
      throw new Error(`Request failed with status ${response?.status ?? "unknown"}`);
    }
    const inventory = buildObjectInfoModelInventory(await response.json());
    if (!inventory) {
      throw new Error("object_info did not expose model loader choices");
    }
    return { ok: true, source: "host-object-info", data: inventory };
  } catch (_error) {
    rookieUIDebugWarn("api.models.object_info", "Host object_info inventory fallback failed.", {
      error: toErrorDetail(_error),
    });
    return null;
  }
}

export async function fetchRookieUIModels(fetchImpl = globalThis.fetch) {
  const result = await fetchRookieUIResource("/rookieui/models", createFallbackModelInventory(), fetchImpl);
  if (result.ok) {
    return result;
  }
  return (await fetchObjectInfoModelInventory(fetchImpl)) ?? result;
}

export async function fetchRookieUIPresets(fetchImpl = globalThis.fetch) {
  return fetchRookieUIResource(
    "/rookieui/presets",
    {
      source: "fallback",
      presets: DEFAULT_PRESETS,
    },
    fetchImpl,
  );
}

export async function fetchRookieUICompatibility(fetchImpl = globalThis.fetch) {
  return fetchRookieUIResource(
    "/rookieui/compatibility",
    {
      source: "fallback",
      samplers: [
        { id: "euler_ancestral", title: "Euler a", tier: "core", default: true, aliases: ["euler a"] },
        { id: "euler", title: "Euler", tier: "core", default: false, aliases: [] },
        { id: "ddim", title: "DDIM", tier: "core", default: false, aliases: [] },
        { id: "dpmpp_2m", title: "DPM++ 2M", tier: "core", default: false, aliases: ["dpm++ 2m"] },
      ],
      schedulers: [
        { id: "normal", title: "Normal", tier: "core", default: true, aliases: ["automatic"] },
        { id: "karras", title: "Karras", tier: "core", default: false, aliases: [] },
        { id: "ddim_uniform", title: "DDIM Uniform", tier: "extended", default: false, aliases: ["ddim"] },
      ],
      runtime_profiles: [
        {
          id: "balanced",
          title: "Balanced",
          summary: "Default RookieUI runtime policy with no extra host-memory hints.",
          default: true,
          experimental: false,
          aliases: [],
        },
      ],
      dtype_profiles: [
        // IMPORTANT: keep this fallback in parity with backend compatibility.py;
        // otherwise transient compatibility-route failures make Diffusion in Low Bits look unsupported.
        {
          id: "automatic",
          title: "Automatic",
          summary: "Use the host default diffusion weight dtype policy.",
          default: true,
          experimental: false,
          aliases: [],
        },
        {
          id: "automatic_fp16_lora",
          title: "Automatic (fp16 LoRA)",
          summary: "Keep the host default dtype while preferring fp16 LoRA execution.",
          default: false,
          experimental: false,
          aliases: [],
        },
        {
          id: "nf4",
          title: "NF4",
          summary: "Optional low-bit diffusion storage hint.",
          default: false,
          experimental: true,
          aliases: [],
        },
        {
          id: "fp4",
          title: "FP4",
          summary: "Optional fp4 diffusion storage hint.",
          default: false,
          experimental: true,
          aliases: [],
        },
        {
          id: "float8_e4m3fn",
          title: "Float8 E4M3FN",
          summary: "Optional float8-e4m3fn storage hint.",
          default: false,
          experimental: true,
          aliases: ["float8-e4m3fn"],
        },
        {
          id: "float8_e5m2",
          title: "Float8 E5M2",
          summary: "Optional float8-e5m2 storage hint.",
          default: false,
          experimental: true,
          aliases: ["float8-e5m2"],
        },
      ],
      newer_family_profiles: DEFAULT_NEWER_FAMILY_PROFILES,
    },
    fetchImpl,
  );
}
